baseURL = 'https://7risten.ca'
languageCode = 'en-us'
title = 'Design & Development'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      table = true
      taskList = true
      typographer = true
      linkify = true
      attributes = true
