// Auto-generated by config.sh
export const MEMORY_PAGES = 2;
export const INPUT = 0x0000;
export const NUM_INPUTS = 4;
export const SPRITE_POS = 0x0008;
export const SPRITE_X_OFFSET = 0;
export const SPRITE_Y_OFFSET = 4;
export const SPRITE_FACING = 0x0010;
export const ROOM_X = 0x0014;
export const ROOM_Y = 0x0018;
export const FACING_RIGHT = 0;
export const FACING_LEFT = 1;
export const FACING_UP = 2;
export const FACING_DOWN = 3;
export const WIDTH = 320;
export const HEIGHT = 180;
export const ROOM_TILE_COLS = 40;
export const ROOM_TILE_ROWS = 22;
export const TILE_PIXEL_WIDTH = 8;
export const TILE_PIXEL_HEIGHT = 8;
export const WORLD_WIDTH = 3;
export const WORLD_HEIGHT = 3;

