// ═══════════════════════════════════════════════════════════════════
// AUTO-GENERATED by educe_transpiler — DO NOT EDIT
// Source: src/engine/scaling.educe
// ES module — import { NAME } from './generated_constants.js'.
// ═══════════════════════════════════════════════════════════════════

export const COMPOSITE_SKY_R = 0.04;
export const COMPOSITE_SKY_G = 0.035;
export const COMPOSITE_SKY_B = 0.06;
export const LIGHTING_AMBIENT_BASE = 0.02;
export const COMPOSITE_GI_STRENGTH = 0.12;
export const COMPOSITE_RIM_BOOST = 0.5;
export const COMPOSITE_RIM_BASE = 0;
export const COMPOSITE_FG_EDGE_GAIN = 1.2;
export const COMPOSITE_FG_EDGE_RIM = 0.1;
export const LIGHT_FLAT_TOP_RADIUS = 0.88;
export const MAX_LIGHTS = 32;
export const LIGHT_GRID_WIDTH = 40;
export const LIGHT_GRID_HEIGHT = 23;
export const LIGHT_ATLAS_SIZE = 512;
export const LIGHT_ATLAS_COLS = 4;
export const LIGHT_ATLAS_ROWS = 4;
export const MAX_SHADOW_TRIS_PER_LIGHT = 512;
export const MAX_VINE_GRASS_VERTICES = 8192;
export const VIEWFINDER_WIDTH = 54;
export const VIEWFINDER_HEIGHT = 54;
export const POLAROID_BORDER_SIDE = 3;
export const POLAROID_BORDER_TOP = 3;
export const POLAROID_BORDER_BOTTOM = 8;
export const POLAROID_CARD_WIDTH = 60;
export const POLAROID_CARD_HEIGHT = 65;
export const GALLERY_INTERMEDIATE_W = 54;
export const GALLERY_INTERMEDIATE_H = 54;
export const GALLERY_CRT_RENDER_W = 216;
export const GALLERY_CRT_RENDER_H = 216;
export const ATLAS_TEXTURE_WIDTH = 512;
export const ATLAS_TEXTURE_HEIGHT = 512;
export const PIXEL_SCALE_S_MIN = 3;
export const PIXEL_SCALE_S_FULL = 6;
export const PIXEL_SCALE_S_HI = 10;
export const PIXEL_SCALE_MASK_CEIL = 0.12;
export const PIXEL_SCALE_HI_BOOST_K = 0.02;
export const CRT_SCALE_OFF_AT = 3;
export const CRT_SCALE_FULL_AT = 6;
export const CRT_SCANLINE_FOLLOWS_SCALE = 0;

// enum game_mode
export const MODE_BOOT_SCREEN = 0;
export const MODE_TELEMETRY_CONSENT = 1;
export const MODE_MAIN_MENU = 2;
export const MODE_SLOT_SELECT = 3;
export const MODE_CONFIRM_DELETE = 4;
export const MODE_CONFIRM_DELETE_2 = 5;
export const MODE_PLAYING = 6;
export const MODE_PAUSED = 7;
export const MODE_PAUSE_SETTINGS = 8;
export const MODE_PAUSE_AUDIO = 9;
export const MODE_SETTINGS = 10;
export const MODE_LANGUAGE_SELECT = 11;
export const MODE_CONTROLS_KEYBOARD = 12;
export const MODE_CONTROLS_GAMEPAD = 13;
export const MODE_REMAPPING_KEY = 14;
export const MODE_REMAPPING_BUTTON = 15;
export const MODE_VIEWFINDER = 16;
export const MODE_GALLERY = 17;
export const MODE_CREDITS = 18;
export const game_mode = Object.freeze({
    MODE_BOOT_SCREEN,
    MODE_TELEMETRY_CONSENT,
    MODE_MAIN_MENU,
    MODE_SLOT_SELECT,
    MODE_CONFIRM_DELETE,
    MODE_CONFIRM_DELETE_2,
    MODE_PLAYING,
    MODE_PAUSED,
    MODE_PAUSE_SETTINGS,
    MODE_PAUSE_AUDIO,
    MODE_SETTINGS,
    MODE_LANGUAGE_SELECT,
    MODE_CONTROLS_KEYBOARD,
    MODE_CONTROLS_GAMEPAD,
    MODE_REMAPPING_KEY,
    MODE_REMAPPING_BUTTON,
    MODE_VIEWFINDER,
    MODE_GALLERY,
    MODE_CREDITS,
});
